### ISSUE TITLE
[Question] Parking Map creation help

### ISSUE THREAD

**Issue by bender2po** [pparmesh/Autonomous-Parking-AV#1]
Hi,
I would like to know how to create a Carla-Map with parking slots. I saw the Map in this repository. I would like build a similar map. Could you tell me: 
1) what tools/softwares needs be installed, 
2) are they open-source?
3) any tutorials?

**Comment by pparmesh** [comment]
The map was created using RoadRunner by Vector Zero. It isn't open source. The software itself is fairly straightforward to use.

**Comment by pparmesh** [comment]
Apparently they are a part of MathWorks now.

**Comment by bender2po** [comment]
> Apparently they are a part of MathWorks now.

Yeah, I have seen the news on Vector Zero's home page.
I am looking for some freeware to create Maps.
